# Generated by Django 4.1 on 2024-02-19 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenthomework',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
