# Generated by Django 4.1 on 2023-11-28 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab3', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BookInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('quality', models.CharField(choices=[('b', 'bad'), ('g', 'good'), ('n', 'new')], max_length=1)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='instances', to='lab3.book')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reader_number', models.CharField(max_length=10)),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('passport_number', models.CharField(max_length=10)),
                ('birth_date', models.DateField()),
                ('address', models.CharField(max_length=200)),
                ('mobile_number', models.CharField(max_length=12)),
                ('education', models.CharField(choices=[('b', 'beginner'), ('m', 'middle'), ('h', 'higher'), ('d', 'degree')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='ReaderRoomHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='rooms_history', to='lab3.reader')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='readers_history', to='lab3.room')),
            ],
        ),
        migrations.CreateModel(
            name='ReaderBookHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('book_instance', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='readers_history', to='lab3.bookinstance')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='books_history', to='lab3.reader')),
            ],
        ),
        migrations.AddField(
            model_name='reader',
            name='book_instances',
            field=models.ManyToManyField(related_name='readers', through='lab3.ReaderBookHistory', to='lab3.bookinstance'),
        ),
        migrations.AddField(
            model_name='reader',
            name='rooms',
            field=models.ManyToManyField(related_name='readers', through='lab3.ReaderRoomHistory', to='lab3.room'),
        ),
        migrations.AddField(
            model_name='bookinstance',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='book_instances', to='lab3.room'),
        ),
        migrations.CreateModel(
            name='BookAuthors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lab3.author')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lab3.book')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(related_name='books', through='lab3.BookAuthors', to='lab3.author'),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='books', to='lab3.publisher'),
        ),
        migrations.AddField(
            model_name='book',
            name='rooms',
            field=models.ManyToManyField(related_name='books', through='lab3.BookInstance', to='lab3.room'),
        ),
        migrations.AddField(
            model_name='book',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='books', to='lab3.section'),
        ),
    ]
