# Generated by Django 4.1 on 2023-11-29 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab3', '0002_author_book_bookinstance_publisher_reader_room_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='registration_date',
            field=models.DateField(),
        ),
    ]
