# Generated by Django 4.1 on 2023-11-30 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab3', '0003_alter_reader_registration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readerbookhistory',
            name='start_date',
            field=models.DateField(blank=True),
        ),
    ]
