# Generated by Django 4.1 on 2023-11-30 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab3', '0004_alter_readerbookhistory_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readerbookhistory',
            name='book_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readers_history', to='lab3.bookinstance'),
        ),
    ]
