# Generated by Django 4.1 on 2024-01-05 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab3', '0007_usermodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
