# Generated by Django 5.0.2 on 2024-03-08 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab3', '0008_delete_testmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='education',
            field=models.CharField(choices=[('b', 'Начальное'), ('m', 'Среднее'), ('h', 'Высшее'), ('d', 'Ученая степень'), ('', 'Нет данных')], max_length=1),
        ),
    ]
